{% set name = "xvec" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xvec-{{ version }}.tar.gz
  sha256: 23639ef4edbee86b10f3758a6436fd1907348baadd935cab35604d4930cd1a6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - xarray >=2022.12.0
    - pyproj >=3.0.0
    - shapely >=2.0b1

test:
  imports:
    - xvec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/xvec
  summary: Vector data cubes for Xarray
  description: |
    Xvec combines Xarray n-D arrays and shapely 2 planar vector geometries
    to create a support for vector data cubes in Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://xvec.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/xvec

extra:
  recipe-maintainers:
    - martinfleis
